### ISSUE TITLE
Feature request sensor state_class: measurement

### ISSUE THREAD

**Issue by jnasholm** [Berlenz/Home-Assistant-ebus-access#3]
Would it be possible to add "state_class: measurement" for sensors defined in "platform: ebus"?

```
sensor:
  - platform: ebus
    sensors:
      - name: "Boiler Supply Line"
        circuit: "430"
        message: "Hc1ActualFlowTempDesired"
        icon: "mdi:thermometer"
        unit_of_measurement: "°C"
        state_class: measurement
```
When I try this to get statistics recorded for plotting the following error is displayed:
`Invalid config for [sensor.ebus]: [state_class] is an invalid option for [sensor.ebus]. Check: sensor.ebus->sensors->6->state_class.`

The current workaround is to process the ebus sensor data through a template sensor.
